[package]
name    = "brook-daemon"
version.workspace = true
edition.workspace = true

[lib]
name = "brook_daemon"
path = "src/lib.rs"

[dependencies]
brook-core = { path = "../brook-core" }
brook-http = { path = "../brook-http" }
brook-api  = { path = "../brook-api" }
brook-proto = { path = "../brook-proto" }
brook-runtime = { path = "../brook-runtime" }
bytes      = { workspace = true }
tokio      = { workspace = true }
tokio-stream = { version = "0.1", features = ["net"] }
tonic      = { workspace = true }
rusqlite   = { workspace = true }
tracing    = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow     = { workspace = true }
thiserror  = { workspace = true }
uuid       = { workspace = true }
fs4        = { workspace = true }
serde      = { workspace = true }
serde_yaml = { workspace = true }
directories = { workspace = true }
clap       = { workspace = true }

[dev-dependencies]
tempfile    = { workspace = true }
async-trait = { workspace = true }
wiremock    = { workspace = true }
