[package]
name    = "brookd"
version.workspace = true
edition.workspace = true

[[bin]]
name = "brookd"
path = "src/main.rs"

[dependencies]
brook-core = { path = "../brook-core" }
brook-http = { path = "../brook-http" }
brook-api  = { path = "../brook-api" }
tokio      = { workspace = true }
rusqlite   = { workspace = true }
tracing    = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow     = { workspace = true }
uuid       = { workspace = true }
