[workspace]
members = [
    "crates/brook-proto",
    "crates/brook-core",
    "crates/brook-api",
    "crates/brook",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
tokio       = { version = "1",    features = ["full"] }
tonic       = { version = "0.12", features = ["transport"] }
prost       = "0.13"
prost-types = "0.13"
