[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-merge-conflict"

[[repos]]
repo = "local"

[[repos.hooks]]
id = "fmt"
name = "cargo fmt"
language = "system"
entry = "cargo fmt"
types = ["rust"]
pass_filenames = false
args = ["--check"]

[[repos.hooks]]
id = "clippy"
name = "cargo clippy"
language = "system"
entry = "cargo clippy"
types = ["rust"]
pass_filenames = false
args = ["--", "-D", "warnings"]

[[repos.hooks]]
id = "protolint"
name = "protolint"
language = "system"
entry = "protolint lint"
files = "\\.proto$"
