[package]
name    = "brook-tui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "brook"
path = "src/main.rs"

[dependencies]
brook-proto  = { path = "../brook-proto" }
tonic        = { workspace = true }
tokio        = { workspace = true }
tokio-stream = { workspace = true }
ratatui      = { workspace = true }
crossterm    = { workspace = true }
anyhow       = { workspace = true }
clap         = { workspace = true }
indexmap     = { workspace = true }
futures-util = { workspace = true }
